x-logging: &default-logging
  driver: "json-file"
  options:
    max-file: "5"
    max-size: "10m"


services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - "127.0.0.1:3000:3000"
    logging: *default-logging


networks:
  default:
    driver: bridge